graph TB
    subgraph Initialize
        direction LR
        A[Begin: Robot enters the beehive] --> B[Trigger smoker]
        B --> P[Move slider and rotate tube to scan beehive interior]
        P --> D[Transmit images to server]
        D --> E[AI analyzes images for honeypots]
        E --> F[Generate 3D honeypot coordinates]
    end
    subgraph Processing
        direction LR
        G{Are there coordinates in the list?}
        G -- Yes --> H[Choose next coordinate]
        H --> I[Provide coordinate to AI]
        I --> J[AI creates instructions]
        J --> L[Robot pinches honeypot]
    end
    subgraph Completion
        direction LR
        S{Is an obstacle present?}
        S -- No --> M[Execute honey extraction]
        S -- Yes --> N
        M --> N[Delete coordinate]
        N --> R{Is harvest threshold reached?}
        R -- No --> G
        R -- Yes --> O[Measure honey, send logs]
        O --> Q[Finish: Robot exits]
    end
    F --> G
    L --> S